### PR TITLE
Add GCC 6.0 compiler

### PR DESCRIPTION
**Pull request by varund7726**

### CODE REVIEW

**Comment by akhilnarang** [comment]
@varund7726  which tc do you use for ROM?
for kernel ubertc 6.0 works fine, tried 5.1 for rom, got a lotta errors

**Comment by varund7726** [comment]
UBER TC 6.0 is expermiental
ive fixed 5.1 for this kernel source
including o3 optis

**Comment by akhilnarang** [comment]
but for rom what do you use

**Comment by varund7726** [comment]
4.9 linaro.
Don't use anything more than 4.9 for rom

**Comment by akhilnarang** [comment]
thanks, was just confirming
 while trying 5.1 got lots of errors , switched to 4.9 half an hour ago, and now its all fine

**Comment by varund7726** [comment]
yup you can try GCC 5.1 kernel with this source
ive fixed the errors

**Pull request merged**
